
CREATE ALIAS mgadm   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgdis   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcld   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcex   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mguni   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgadt   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mginv   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgind   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmfg   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmnt   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmrp   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgrac   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgtmp   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgven   FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS movadm  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movdis  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movind  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmfg  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmnt  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movrac  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS wmovdis FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS mgesp   FOR DATABASE emsesp NO-ERROR.
CREATE ALIAS mgfis   FOR DATABASE mgcad NO-ERROR.
 
RUN web/objects/web-disp.p.

QUIT.
